config/routes.rb
Linksapp::Application.routes.draw do

  match '/:action.appcache', :controller => 'appcache', :format => :appcache

  match '/auth/twitter/callback' => 'site#process_twitter_callback'
  match '/add' => 'links#add', :as => 'links_add'
  match '/site/no_welcome' => 'site#no_welcome', :as => 'no_welcome'
  match '/links/page/:page' => 'links#index'

  devise_for :users, :controllers => {:registrations => "users"}

  resources :links do
    resources :comments
    resources :likes
  end
  resources :sources
  resources :users

  root :to => 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, :counter_cache => true
  belongs_to :link, :counter_cache => true, :touch => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :js

  def create
    @link = Link.find(params[:link_id])
    comment = @link.comments.build(params[:comment])
    comment.user = current_user
    comment.save!
    respond_with(@link.reload)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
  .user
    = image_tag comment.user.avatar.url(:large)
    %h3
      = link_to comment.user.nickname, user_path(comment.user), :class => 'pjax'
  .body
    = comment.body.gsub(/\n/, "<br/>").html_safe
  .minor
    %span.timeago{:title => comment.created_at.to_time.iso8601}
    -# The above JS timeago is refreshed by the inline js in the link/show.html

app/views/comments/_new.html.haml
= image_tag current_user.avatar.url(:large)
= form_for(Comment.new, :url => link_comments_path(@link), :remote => true, :id => 'new-comment-form') do |f|
  %fieldset
    #errors{:style => 'display:none'}
    %div
      = f.text_area :body, :rows => 4, :id => "comment-body-textarea", :placeholder => "Add a comment"
    .form-controls
      = f.submit :class => 'btn btn-primary', :value => "Add comment", :id => 'comment-submit', :style => 'display:none;'