config/routes.rb
Linksapp::Application.routes.draw do

  match '/:action.appcache', :controller => 'appcache', :format => :appcache

  match '/auth/twitter/callback' => 'site#process_twitter_callback'
  match '/add' => 'links#add', :as => 'links_add'
  match '/site/no_welcome' => 'site#no_welcome', :as => 'no_welcome'
  match '/links/page/:page' => 'links#index'

  devise_for :users, :controllers => {:registrations => "users"}

  resources :links do
    resources :comments
    resources :likes
  end
  resources :sources
  resources :users

  root :to => 'links#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :links
  has_many :likes, :dependent => :destroy
  has_many :liked_links, :through => :likes, :source => :link
  has_many :comments, :dependent => :destroy
  has_many :commented_links, :through => :comments, :source => :comment # TODO: these aren't unique when returned

  validates_presence_of :email, :nickname
  validates_uniqueness_of :email
  validate :invite_code_is_valid
  validate :password_validation

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable #, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :twitter_uid,
                  :twitter_oauth_token, :twitter_oauth_secret, :twitter_nickname, :nickname, :name,
                  :show_welcome, :invite_code, :avatar

  has_attached_file :avatar,
    :styles => {
      :square   => "48x48^",
      :small    => "16x16>",
      :medium   => "24x24>",
      :large    => "48x48>",
    },
    :convert_options => {
      :square      => "-gravity center -extent 48x48",
      :all         => '-auto-orient'
    },
    :storage        => :s3,
    :bucket         => 'barrymitchelson_linksapp_us',
    :path           => "images/:id/:style/:filename",
    :s3_credentials => {
      :access_key_id     => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
  }

  def invite_code_is_valid
    if self.invite_code != 'blahblahblah'
      errors.add(:invite_code, 'is invalid')
    end
  end

  def password_validation
    if new_record?
      errors.add(:password, "can't be blank") if self.password.blank?
    end
  end

  def set_avatar_from_url image_url
    io = open(URI.parse(image_url))
    def io.original_filename; base_uri.path.split('/').last; end
    self.avatar = io.original_filename.blank? ? nil : io
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(
      :email       => params[:email],
      :nickname    => params[:nickname],
      :password    => params[:password],
      :invite_code => params[:invite_code]
    )

    if !params[:avatar_url].blank?
      @user.set_avatar_from_url(params[:avatar_url])
    elsif params[:avatar]
      @user.avatar = params[:avatar]
    end

    if @user.valid?
      @user.save!
      sign_in_and_redirect(:user, @user)
    else
      render :new
    end
  end

  def update
    @user = current_user
    attr = {
      :email => params[:email],
      :nickname => params[:nickname]
    }

    if !params[:password].blank?
      attr.merge!(:password => params[:password])
    end


    if !params[:avatar_url].blank?
      @user.set_avatar_from_url(params[:avatar_url])
    elsif params[:avatar]
      attr.merge!(:avatar => params[:avatar])
    end

    @user.attributes = attr
    if @user.valid?
      @user.save
      sign_in(@user, :bypass => true)
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.control-group{:class => (error_on(@user, :nickname) ? 'error' :'')}
  = label_tag :nickname, nil, :class => 'control-label'
  .controls
    = text_field_tag :nickname, @user.nickname
    - if error_on(@user, :nickname)
      %span.help-inline
        = errors_for(@user, :nickname)
.control-group{:class => (error_on(@user, :email) ? 'error' :'')}
  = label_tag :email, nil, :class => 'control-label'
  .controls
    = text_field_tag :email, @user.email
    - if error_on(@user, :email)
      %span.help-inline
        = errors_for(@user, :email)
.control-group{:class => (error_on(@user, :password) ? 'error' :'')}
  = label_tag :password, nil, :class => 'control-label'
  .controls
    = password_field_tag :password, @user.password
    - if error_on(@user, :password)
      %span.help-inline
        = errors_for(@user, :password)
.control-group{:class => (error_on(@user, :avatar) ? 'error' :'')}
  = label_tag :avatar, nil, :class => 'control-label'
  .controls
    - if @user.avatar?
      %p
        = image_tag @user.avatar.url(:large)
    = file_field_tag :avatar
    = text_field_tag :avatar_url, nil, :placeholder => 'Paste your URL here', :id => 'avatar_url', :style => 'display:none;'
    %p.help-block
      %a{:href => '#', :id => 'avatar_type'}use URL
    - if error_on(@user, :avatar)
      %span.help-inline
        = errors_for(@user, :avatar)

app/views/users/edit.html.haml
%h1 Edit

- unless @user.errors.blank?
  .alert.alert-error
    %strong Oops!
    Some errors occurred.

= form_tag(user_path(@user), :method => :put, :multipart => true, :class => 'form-horizontal') do
  %fieldset
    = render :partial => 'users/form'
    .control-group
      .controls
        = submit_tag "Save", :class => "btn btn-primary"

.alert.alert-info
  %h4.alert-heading Twitter
  - if @user.twitter_uid
    %p
      You're linked to
      = link_to "@#{@user.twitter_nickname}", "http://twitter.com/#{@user.twitter_nickname}"
  - else
    %p
      Linking your account allows you to login via Twitter, and in the future some other awesome features.
    %p
      %a{:href => '/auth/twitter?type=link_account', :class => 'btn btn-twitter'}
        = image_tag('bird_16_blue.png')
        Link

app/views/users/new.html.haml
%h1 Sign Up

- unless @user.errors.blank?
  .alert.alert-error
    %strong Oops!
    Some errors occurred.

-# %form.form-horizontal{:method => :post, :action => user_registration_path}
= form_tag(users_path, :method => :post, :multipart => true, :class => 'form-horizontal') do
  %fieldset
    = render :partial => 'users/form'
    .control-group{:class => (error_on(@user, :invite_code) ? 'error' :'')}
      = label_tag :invite_code, nil, :class => 'control-label'
      .controls
        = text_field_tag :invite_code, @user.invite_code
        - if error_on(@user, :invite_code)
          %span.help-inline
            = errors_for(@user, :invite_code)
    .control-group
      .controls
        = submit_tag "Sign up", :class => "btn btn-primary"

app/views/users/show.html.haml
%div
  - if @user.avatar?
    = image_tag @user.avatar.url(:large)
  %h1
    = @user.nickname

%h2 Shared #{pluralize(@user.links_count, 'link')}

%p
  More coming soon.