config/routes.rb
Linksapp::Application.routes.draw do

  match '/:action.appcache', :controller => 'appcache', :format => :appcache

  match '/auth/twitter/callback' => 'site#process_twitter_callback'
  match '/add' => 'links#add', :as => 'links_add'
  match '/site/no_welcome' => 'site#no_welcome', :as => 'no_welcome'
  match '/links/page/:page' => 'links#index'

  devise_for :users, :controllers => {:registrations => "users"}

  resources :links do
    resources :comments
    resources :likes
  end
  resources :sources
  resources :users

  root :to => 'links#index'

end

app/models/link.rb
require 'open-uri'
require 'yajl'

class Link < ActiveRecord::Base

  belongs_to :user, :counter_cache => true
  belongs_to :source, :counter_cache => true

  has_many :likes, :dependent => :destroy
  has_many :likers, :through => :likes, :source => :user

  has_many :comments, :dependent => :destroy
  has_many :commenters, :through => :comments, :source => :user

  before_create :parse

  VIDEO_HOSTS = ['www.youtube.com', 'vimeo.com']

  has_attached_file :image,
    :styles => {
      :thumbnail    => "280x140^",
      :website_main => "700x700>"
    },
    :convert_options => {
      :all         => '-auto-orient',
      :thumbnail   => "-gravity center -extent 280x140"
    },
    :storage        => :s3,
    :bucket         => 'barrymitchelson_linksapp_us',
    :path           => "images/:id/:style/:filename",
    :s3_credentials => {
      :access_key_id     => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
  }

  def self.most_recently_updated
    self.order(:updated_at).last
  end

  def likes_count
    read_attribute(:likes_count) || 0
  end

  def comments_count
    read_attribute(:comments_count) || 0
  end

  def parse
    set_source
    clean_title!
    clean_url!
    set_image_video
    create_thumbnail
  end

  def uri
    @uri ||= URI.parse(self.url)
  end

  def params
    @params if @params
    if self.uri.query
      @params = CGI.parse(self.uri.query)
    else
      @params = []
    end
  end

  def is_liked?
    self.likes_count && self.likes_count > 0
  end

  def has_comments?
    self.comments_count && self.comments_count > 0
  end

  def is_media?
    is_video? || is_image?
  end

  def set_image_video
    self.is_video = VIDEO_HOSTS.include?(uri.host)
    self.is_image = !!(self.url =~ /\.(jpg|jpeg|gif|png)$/i)
  end

  def is_youtube?
    uri.host == 'www.youtube.com'
  end

  def is_vimeo?
    uri.host == 'vimeo.com'
  end

  def embed_code(size = :default)
    return youtube_embed_code(size) if is_youtube?
    return vimeo_embed_code(size) if is_vimeo?
  end

  # TODO: this should probably be in source as well
  def youtube_embed_code(size)
    width, height = video_embed_size(size)
    "<iframe id='embedded_video' width='#{width}' height='#{height}' src='http://www.youtube.com/embed/#{self.params['v'][0]}?autohide=1&hd=1&border=1&showinfo=0' frameborder='0' allowfullscreen></iframe>".html_safe
  end

  def vimeo_embed_code(size)
    width, height = video_embed_size(size)
    "<iframe id='embedded_video' src=\"http://player.vimeo.com/video/#{self.vimeo_id}?title=0&byline=0&portrait=0\" width=\"#{width}\" height=\"#{height}\" frameborder=\"0\"></iframe>".html_safe
  end

  def video_embed_size(size)
    case size
    when :default
      width, height = 420, 315
    when :small
      width, height = 280, 236
    when :large
      # width, height = 900, 520
      width, height = 700, 404
    end
    [width, height]
  end

  def set_source
    self.source = Source.find_or_create_by_url(self.uri.host)
  end

  def create_thumbnail
    if is_image?
      set_image(self.url)
    elsif is_youtube?
      data = Yajl::Parser.parse(open(URI.parse("http://gdata.youtube.com/feeds/api/videos/#{self.params['v'][0]}?v=2&alt=jsonc")))
      set_image(data['data']['thumbnail']['hqDefault'])
    elsif is_vimeo?
      data = Yajl::Parser.parse(open(URI.parse("http://vimeo.com/api/v2/video/#{self.vimeo_id}.json")))
      set_image(data[0]['thumbnail_large'])
    end
  end

  def vimeo_id
    self.url =~ /vimeo\.com\/(\d*)/
    $1
  end

  def set_image(image_url)
      io = open(URI.parse(image_url))
      def io.original_filename; base_uri.path.split('/').last; end
      self.image = io.original_filename.blank? ? nil : io
  end

  def clean_title!
    self.title = self.source.clean_link_title(self.title)
  end

  # TODO: this should be in source
  def clean_url!
    remove_urchin
    case uri.host
    when 'www.youtube.com'
      self.url = "#{uri.scheme}://#{uri.host}/watch?v=#{self.params['v'][0]}"
    when 'boingboing.net'
      self.url = "#{uri.scheme}://#{uri.host}#{uri.path}"
    end
  end

  def remove_urchin
    cleaned_params = self.params.select {|p| p !~ /^utm_/}
    self.url = "#{uri.scheme}://#{uri.host}#{uri.path}"
    if !cleaned_params.empty?
      qs = cleaned_params.map {|k,v| v.map{|val| "#{k}=#{CGI.escape(val)}"}}.flatten.join("&")
      self.url = self.url + "?#{qs}"
    end
    self.url = self.url + uri.fragment.to_s
  end

  def self.reparse_all!
    self.all.each {|l| l.parse;l.save!}
  end

  def liked_by?(user)
    self.likers.include? user
  end

  def twitter_share_url_for(sharing_user)
    twitter_url = "https://twitter.com/share?url=#{CGI.escape(self.url)}&text=#{CGI.escape(self.title)}&size=large"
    if sharing_user != self.user
      twitter_url += "&via=#{self.user.nickname}"
    end
    twitter_url
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :authenticate_user!

  respond_to :html, :json, :js

  def add
    if !params[:url]
    else
      link = Link.find_by_url(params[:url])
      if link
        flash[:notice] = "This link has already been shared, a like has been added for you to the original post. THIS DOES NOT WORK."
        redirect_to link_path(link)
      else
        link = current_user.links.build(:url => params[:url], :title => params[:title], :type => 'website')
        link.save!
        redirect_to link_path(link)
      end
    end
  end

  def show
    @link = Link.find(params[:id])
    # if stale?(:last_modified => @link.updated_at.utc, :etag => [@link, current_user])
      respond_with @link
    # end
  end

  def index
    # @index_cache_key = ["links", "all", Link.most_recently_updated]
    @links = Link.order('updated_at desc').page(params[:page]).per(20)

    # logger.info @links.first.updated_at.utc
    # if stale?(:last_modified => @links.first.updated_at.utc, :etag => [@links.first, current_user])
      logger.info "stale"
      respond_with @links
    # end
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_likers.html.haml
- if link.is_liked?
  %h3 Likers
  %p
    - link.likers.each do |liker|
      = image_tag liker.avatar.url(:large), :id => "liker_#{liker.id}"

app/views/links/_link.html.haml
- cache ["v2", link, link.user] do
  .preview
    .submitter
      = image_tag link.user.avatar.url(:square)
    .details{:class => link.is_media? ? 'media' : ''}
      %h4
        = link_to link.title, link_path(link), :class => 'pjax'
      %div= link.source.display_name
      %div
        %span.reaction{:class => (link.likes_count > 0 ? 'some': '')}
          -# %i.icon-heart
          -# = link.likes_count
          = pluralize(link.likes_count, 'like')
        %span.reaction{:class => (link.comments_count > 0 ? 'some': '')}
          -# %i.icon-comment
          -# = link.comments_count
          = pluralize(link.comments_count, 'comment')
        %span.minor
          %span.timeago{:title => link.updated_at.to_time.iso8601}
    - if link.is_media?
      = link_to image_tag(link.image.url(:thumbnail), :class => 'media'), link_path(link), :class => 'pjax'

app/views/links/index.html.haml
- if current_user.show_welcome?
  #welcome.hero-unit
    %h1 Welcome!
    %p
      Sharing links is easy, just <strong>drag the button</strong> below on to your toolbar and click it when you're on a page you want to share.

    %br
    %p
      %a.btn.bookmarklet(href="javascript:function la(){ var d=document,s=d.createElement('scr'+'ipt'),b=d.body; try { if(!b)throw(0); s.setAttribute('src', '#{links_add_url}'); b.appendChild(s); } catch(e) { alert('You need to let the page load first'); } } la();")Share on linksapp
    #bookmarklet-help.alert.alert-error{:style => 'display:none'}
      %p
        You're an idiot. It clearly says <strong>drag</strong> the button, not click it. Or do you just click things without reading the instructions?
      %p
        %a#dont-click.btn Do not click this
    %br
    %p
      = link_to "OK, got it. Never show me this again.", no_welcome_path, :remote => true, :class => "btn btn-success", :id => 'ok'

-# - cache ["v1", @index_cache_key] do
- @links.group_by {|l| l.updated_at.at_beginning_of_day}.each do |day, links|
  .day
    %h1
      = day.strftime("%A")
      %small= day.strftime("%e %b")
    = render links

= paginate @links

:javascript
  $($('.timeago').timeago());

app/views/links/show.html.haml
.link
  .inner
    %h1
      = link_to @link.title, @link.url

    - if @link.is_video?
      = @link.embed_code(:large)

    - if @link.is_image?
      = image_tag(@link.image.url(:website_main))

    %p
      = link_to @link.user.nickname, user_path(@link.user), :class => 'pjax'
      shared this
      %span.timeago{:title => @link.created_at.to_time.iso8601}
      from #{link_to(@link.source.display_name, source_path(@link.source), :class => 'pjax')}
      - if @link.source.links_count > 1
        ( #{pluralize(@link.source.links_count - 1, 'more link')} )

    %p
      - if @link.liked_by?(current_user)
        = link_to "Like", link_likes_path(@link), :remote => true, :method => :post, :class => "btn btn-success", :id => 'like'
      - else
        = link_to "Like", link_likes_path(@link), :remote => true, :method => :post, :class => "btn", :id => 'like'

      %a.btn.popup.btn-twitter{:href => @link.twitter_share_url_for(current_user)}
        = image_tag('bird_16_blue.png')
        Tweet
      = link_to "Instapaper", "http://www.instapaper.com/hello2?url=#{CGI.escape(@link.url)}&title=#{CGI.escape(@link.title)}", :class => "btn"
      -# %a.btn.disabled Favourite
      -# %a.btn.disabled Email

    #likers
      = render :partial => 'links/likers', :locals => {:link => @link}

    #comments
      = render @link.comments
    #new-comment-form
      = render :partial => 'comments/new', :locals => {:link => @link}
:javascript
  $($('.timeago').timeago());