config/routes.rb
Linksapp::Application.routes.draw do

  match '/:action.appcache', :controller => 'appcache', :format => :appcache

  match '/auth/twitter/callback' => 'site#process_twitter_callback'
  match '/add' => 'links#add', :as => 'links_add'
  match '/site/no_welcome' => 'site#no_welcome', :as => 'no_welcome'
  match '/links/page/:page' => 'links#index'

  devise_for :users, :controllers => {:registrations => "users"}

  resources :links do
    resources :comments
    resources :likes
  end
  resources :sources
  resources :users

  root :to => 'links#index'

end

app/views/layouts/application.html.haml
!!!
%html
  -# {:manifest => "/#{Rails.env}.appcache"}
  %head>
    %title Linksapp
    = stylesheet_link_tag    "application"
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="black")
  %body
    .header-hack
    .container
      .content
        .row
          .span10.offset1
            .header
              -# = image_tag('logo.png')
              %h2 Linksapp
            .row
              .span8
                #alerts
                  - if flash[:notice]
                    .alert.alert-info
                      = flash[:notice]
                  - if flash[:error]
                    .alert.alert-error
                      = flash[:error]
                  - if flash[:success]
                    .alert.alert-success
                      = flash[:success]
                  - if flash[:alert] && flash[:alert] != 'You need to sign in or sign up before continuing.'
                    .alert.alert-error
                      = flash[:alert]
                #main
                  =yield
              .span2
                .sidebar
                  - if user_signed_in?
                    .user
                      - if current_user.avatar?
                        = image_tag current_user.avatar.url(:square)
                      %ul.nav.nav-list
                        %li.nav-header
                          = current_user.nickname
                        %li= link_to "Your profile", user_path(current_user), :class => 'pjax'
                        %li= link_to "Your account", edit_user_path(current_user), :class => 'pjax'
                        %li= link_to "Sign out", destroy_user_session_path, :method => :delete

  :javascript
    $($('.dropdown-toggle').dropdown())